apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ randAlphaNum 8 | b64enc }}
  DB_PASSWORD: {{ randAlphaNum 40 | b64enc }}