apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-api
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http-logs
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http-soap
  selector:
    {{- include "spring-boot-api.selectorLabels" . | nindent 4 }}
