apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev-global-cluster-0
        env: dev
        url: https://kubernetes.default.svc
      - cluster: prd-global-cluster-5
        env: prd
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'spring-boot-api-{{.env}}'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/pio-janik/spring-boot-api.git'
          targetRevision: main
          ref: values
        - repoURL: 'https://github.com/pio-janik/spring-boot-api.git'
          path: helm-chart
          targetRevision: main
          helm:
            valueFiles:
            - $values/config/{{ .cluster }}/values.yaml
      destination:
        server: '{{ .url }}'
        namespace: team-java
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true